# start middleware for local test
version: '2'
services:
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: console
        MYSQL_ROOT_PASSWORD: console
        MYSQL_USER: console
        MYSQL_PASSWORD: console
      ports:
        - 3306:3306
      volumes:
        - ./mysql/ddl:/docker-entrypoint-initdb.d
        - ./mysql/conf:/etc/mysql
